language: objective-c
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - PROJECT=AlamofireNetworkActivityIndicator.xcodeproj
  - IOS_SCHEME="AlamofireNetworkActivityIndicator"
  - IOS_SIM="iphonesimulator"
matrix:
  include:
    - os: osx
      osx_image: xcode7.3
      env: DESTINATION="OS=8.1,name=iPhone 4S" SCHEME="$IOS_SCHEME" SDK="${IOS_SIM}9.3" RUN_TESTS="YES" POD_LINT="YES"
    - os: osx
      osx_image: xcode7.3
      env: DESTINATION="OS=8.2,name=iPhone 5" SCHEME="$IOS_SCHEME" SDK="${IOS_SIM}9.3" RUN_TESTS="YES" POD_LINT="NO"
    - os: osx
      osx_image: xcode7.3
      env: DESTINATION="OS=8.3,name=iPhone 5S" SCHEME="$IOS_SCHEME" SDK="${IOS_SIM}9.3" RUN_TESTS="YES" POD_LINT="NO"
    - os: osx
      osx_image: xcode7.3
      env: DESTINATION="OS=8.4,name=iPhone 6" SCHEME="$IOS_SCHEME" SDK="${IOS_SIM}9.3" RUN_TESTS="YES" POD_LINT="NO"
    - os: osx
      osx_image: xcode7.3
      env: DESTINATION="OS=9.0,name=iPhone 6" SCHEME="$IOS_SCHEME" SDK="${IOS_SIM}9.3" RUN_TESTS="YES" POD_LINT="NO"
    - os: osx
      osx_image: xcode7.3
      env: DESTINATION="OS=9.1,name=iPhone 6 Plus" SCHEME="$IOS_SCHEME" SDK="${IOS_SIM}9.3" RUN_TESTS="YES" POD_LINT="NO"
    - os: osx
      osx_image: xcode7.3
      env: DESTINATION="OS=9.2,name=iPhone 6S" SCHEME="$IOS_SCHEME" SDK="${IOS_SIM}9.3" RUN_TESTS="YES" POD_LINT="NO"
    - os: osx
      osx_image: xcode7.3
      env: DESTINATION="OS=9.3,name=iPhone 6S Plus" SCHEME="$IOS_SCHEME" SDK="${IOS_SIM}9.3" RUN_TESTS="YES" POD_LINT="NO"

    - os: osx
      env: DESTINATION="OS=10.0,name=iPhone 6S" SCHEME="$IOS_SCHEME" SDK="${IOS_SIM}10.0" RUN_TESTS="YES" POD_LINT="NO"
      osx_image: xcode8
script:
  - set -o pipefail
  - git submodule update --init --recursive
  - xcodebuild -version
  - xcodebuild -showsdks

  # Build Framework in Debug and Run Tests
  - xcodebuild -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c;
  
  # Build Framework in Release and Run Tests  
  - xcodebuild -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration ReleaseTest ONLY_ACTIVE_ARCH=NO test | xcpretty -c;

  # Run `pod lib lint` if specified
  - if [ $POD_LINT == "YES" ]; then
      pod lib lint;
    fi
